name: Code coverage and Static Analysis
on:
  # For Sonarcloud PR decoration to work, trigger must be pull_request.
  # This is the most common way to trigger the sonarcloud flow.
  pull_request:
    types: [ opened, synchronize, reopened ]
  # For Sonarcloud to keep track of "main branch" to compare PRs against, we need to trigger SonarCloud on pushes to
  # that branch.
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload
      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}